# Generated by Django 6.0.3 on 2026-04-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('merchandiser', 'Товаровед'), ('admin', 'Администратор')], default='buyer', max_length=20, verbose_name='Роль'),
        ),
    ]
