# Generated by Django 6.0.3 on 2026-04-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_views_count_profile_last_login_at_profile_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'book')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
