# Generated by Django 5.2 on 2026-05-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartitem_quantity_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения оплаты'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('ordered', 'Заказана'), ('paid', 'Оплачена'), ('completed', 'Завершена'), ('abandoned', 'Заброшена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Заказ'), ('payment', 'Оплата'), ('sale', 'Акция'), ('info', 'Информация')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
