# Generated by Django 5.2 on 2026-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_file_order_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на Google Docs или Google Drive файл', max_length=500, null=True, verbose_name='Ссылка на файл книги (Google Docs/Drive)'),
        ),
    ]
