# Generated by Django 5.2 on 2026-05-13 05:44

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_book_file_book_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_url',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, help_text='Загрузите файл книги (PDF, EPUB, TXT, HTML)', null=True, upload_to=store.models.book_file_upload_path, verbose_name='Файл книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('txt', 'TXT'), ('html', 'HTML')], default='pdf', help_text='Тип загружаемого файла', max_length=10, verbose_name='Тип файла'),
        ),
    ]
