# Generated by Django 5.2 on 2026-05-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_book_book_url_book_book_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='book',
        ),
        migrations.AddField(
            model_name='sale',
            name='books',
            field=models.ManyToManyField(related_name='sales', to='store.book', verbose_name='Книги'),
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация об акции', verbose_name='Описание акции'),
        ),
    ]
